services:
  nginx:
    environment:
      WEB_HOST: ${WEB_HOST}
      API: ${API}
    image: uka17/envault-nginx:latest
    container_name: envault-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot-webroot:/var/www/certbot:ro
    networks:
      envault_network:
        ipv4_address: ${WEB_HOST}

networks:
  envault_network:
    external: true
